FROM tensorflow/tensorflow

RUN pip3 install gunicorn
RUN pip3 install pandas
RUN pip3 install flask
RUN pip3 install Flask-SQLAlchemy
RUN pip3 install protobuf==3.20.*

COPY . .
CMD [ "flask", "run"]
